// Command tzgen writes the list of IANA time zone names offered in the
// panel, taken from the Go distribution's zoneinfo.zip.
//
// Usage: go run ./tools/tzgen > internal/panel/i18n/zones.go
package main

import (
	"archive/zip"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
)

// regions are the geographic areas of canonical zone names. Legacy aliases
// such as "US/Eastern" and "Etc/GMT+5" are left out.
var regions = []string{
	"Africa", "America", "Antarctica", "Arctic", "Asia",
	"Atlantic", "Australia", "Europe", "Indian", "Pacific",
}

func main() {
	zr, err := zip.OpenReader(filepath.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip"))
	if err != nil {
		fmt.Fprintln(os.Stderr, "tzgen:", err)
		os.Exit(1)
	}
	defer zr.Close()

	names := []string{"UTC"}
	for _, f := range zr.File {
		region, _, ok := strings.Cut(f.Name, "/")
		if ok && slices.Contains(regions, region) {
			names = append(names, f.Name)
		}
	}
	slices.Sort(names[1:])

	fmt.Println("// Code generated by tools/tzgen; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package i18n")
	fmt.Println()
	fmt.Println("// TimeZones lists the IANA time zones offered in the panel, UTC first.")
	fmt.Println("var TimeZones = []string{")
	for _, n := range names {
		fmt.Printf("\t%q,\n", n)
	}
	fmt.Println("}")
}
